Lyon add links objects
eiffel-community/eiffelevents-sdk-dotnet pull request #47
Opened 2021-12-30 09:13 UTC by AhmedAbouElfotouh

### Applicable Issues

N/A
### Description of the Change

Add Lyon Link objects.

### Alternate Designs

N/A
### Benefits

Link objects will be used in all new Lyon edition events.
### Possible Drawbacks

N/A
### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Ahmed Abou Elfotouh ahmed.fotouh@live.com

2022-01-01 11:37 UTC, erkist requested changes

2022-01-01 11:37 UTC, erkist commented on src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelArtifact Link.cs
> +        public EiffelArtifactLink(string target, string domainId = "") : base(target, domainId)
Please add XmlDoc to all constructors

2022-01-04 15:50 UTC, fadykamil submitted a review, later dismissed

2022-01-06 11:00 UTC, erkist approved these changes

2022-01-06 11:09 UTC, merged